<h2>Add a product type</h2>

<form method="post" action="<?php $helper->routing->route([ "product-types" ] , "add"); ?>">

    <table class="form table">
        <tr>
            <td><?php $helper->form->label($form->getField("name"), "Name"); ?></td>
            <td><?php $helper->form->textField($form->getField("name")); ?></td>
        </tr>
    </table>

    <button type="submit">Save</button>
    <button type="button" onclick="history.back()">Cancel</button>

</form>
