<h2>Edit product type</h2>

<ul class="tabs">
    <li><a href="/product-types/<?php echo $item->id; ?>">Product type</a></li>
    <li class="active"><a href="/product-types/<?php echo $item->id; ?>/edit">Edit</a></li>
    <li><a href="/product-types/<?php echo $item->id; ?>/attributes">Attributes</a></li>
</ul>

<form method="post" action="/product-types/edit/<?php echo $item->id; ?>">

    <?php $helper->form->textField($form->getField("name"), "Name"); ?>

    <button type="submit">Save</button>
    <button type="button" onclick="history.back()">Cancel</button>

</form>
