<h2>Product types</h2>

<table class="index table">
    <thead>
        <tr>
            <th>Product type</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $type): ?>
        <tr>
            <td><a href="/product-types/<?php echo $type->id; ?>"><?php echo $type->name; ?></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="/product-types/add" class="button">Add product type</a></p>
