<h2>Product types</h2>

<table class="index table">
    <thead>
        <tr>
            <th>Product type</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $type): ?>
        <tr>
            <td><a href="<?php $helper->routing->route([ "product-types" => $type->id ]); ?>"><?php echo $type->name; ?></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="<?php $helper->routing->route([ "product-types" ] , "add"); ?>" class="button">Add product type</a></p>
