<h2>Product type</h2>

<ul class="tabs">
    <li class="active"><a href="/product-types/<?php echo $item->id; ?>">Product type</a></li>
    <li><a href="/product-types/<?php echo $item->id; ?>/edit">Edit</a></li>
    <li><a href="/product-types/<?php echo $item->id; ?>/attributes">Attributes</a></li>
</ul>

<table class="detail table">
    <tr>
        <td>Name</td>
        <td><?php echo $item->name; ?></td>
    </tr>
</table>

<p>
    <a href="/product-types/<?php echo $item->id; ?>/edit" class="button">Edit</a>
    <a href="/product-types/<?php echo $item->id; ?>/delete" class="button">Delete</a>
</p>
<p><a href="/product-types">Back to index</a></p>
