<h2>Product type</h2>

<ul class="tabs">
<?php foreach ($subnav->getChildren() as $node): ?>
    <li <?php if ($node->active) echo ' class="active"'; ?>><a href="<?php echo $node->url; ?>"><?php echo $node->label; ?></a></li>
<?php endforeach; ?>
</ul>

<table class="detail table">
    <tr>
        <td>Name</td>
        <td><?php echo $item->name; ?></td>
    </tr>
</table>

<p>
    <a href="<?php $helper->routing->route([ "product-types" => $item->id ] , "edit"); ?>" class="button">Edit</a>
    <a href="<?php $helper->routing->route([ "product-types" => $item->id ] , "delete"); ?>" class="button">Delete</a>
</p>
<p><a href="<?php $helper->routing->route([ "product-types" ]); ?>">Back to index</a></p>
