<h2>Edit product</h2>

<ul class="tabs">
<?php foreach ($subnav->getChildren() as $node): ?>
    <?php if (!$node->hidden): ?>
    <li <?php if ($node->active) echo ' class="active"'; ?>><a href="<?php echo $node->url; ?>"><?php echo $node->label; ?></a></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>

<form method="post" action="<?php $helper->routing->route([ "products" => $parentItem->id, "variants" => $item->id ], "edit"); ?>">

    <table class="form table">
        <tr>
            <td><?php $helper->form->label($form->getField("title"), "Title"); ?></td>
            <td><?php $helper->form->textField($form->getField("title")); ?></td>
        </tr>
        <tr>
            <td><?php $helper->form->label($form->getField("base_price"), "Base price"); ?></td>
            <td><?php $helper->form->textField($form->getField("base_price")); ?></td>
        </tr>
        <tr>
            <td><?php $helper->form->label($form->getField("sku"), "SKU"); ?></td>
            <td><?php $helper->form->textField($form->getField("sku")); ?></td>
        </tr>
        <tr>
            <td><?php $helper->form->label($form->getField("gtin"), "GTIN"); ?></td>
            <td><?php $helper->form->textField($form->getField("gtin")); ?></td>
        </tr>
    </table>

    <button type="submit">Save</button>
    <button type="button" onclick="history.back()">Cancel</button>

</form>
