<h2>Variants of <?php echo $parentItem->title; ?></h2>

<ul class="tabs">
<?php foreach ($subnav->getChildren() as $node): ?>
    <?php if (!$node->hidden): ?>
    <li <?php if ($node->active) echo ' class="active"'; ?>><a href="<?php echo $node->url; ?>"><?php echo $node->label; ?></a></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>

<table class="index table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Base price</th>
            <th>SKU</th>
            <th>GTIN</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $product): ?>
        <tr>
            <td><a href="<?php $helper->routing->route([ "products" => $parentItem->id, "variants" => $product->id ]); ?>"><?php echo $product->title; ?></a></td>
            <td><?php echo $product->base_price; ?></td>
            <td><?php echo $product->sku; ?></td>
            <td><?php echo $product->gtin; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="<?php $helper->routing->route([ "products" => $parentItem->id, "variants" ], "add"); ?>" class="button">Add variant</a></p>
