<h2>Variants of <?php echo $parentItem->title; ?></h2>

<ul class="tabs">
    <li><a href="<?php $helper->routing->route([ "products" => $parentItem->id ]); ?>">Product</a></li>
    <li><a href="<?php $helper->routing->route([ "products" => $parentItem->id ], "edit"); ?>">Edit</a></li>
    <li class="active"><a href="<?php $helper->routing->route([ "products" => $parentItem->id, "variants" ]); ?>">Variants</a></li>
</ul>

<table class="index table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Base price</th>
            <th>SKU</th>
            <th>GTIN</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $product): ?>
        <tr>
            <td><a href="<?php $helper->routing->route([ "products" => $parentItem->id, "variants" => $product->id ]); ?>"><?php echo $product->title; ?></a></td>
            <td><?php echo $product->base_price; ?></td>
            <td><?php echo $product->sku; ?></td>
            <td><?php echo $product->gtin; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="<?php $helper->routing->route([ "products" => $parentItem->id, "variants" ], "add"); ?>" class="button">Add variant</a></p>
