<h2>Languages</h2>

<table class="index table">
    <thead>
        <tr>
            <th>Language</th>
            <th>Localized name</th>
            <th>Language code</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $language): ?>
        <tr>
            <td><a href="<?php $helper->routing->route([ "languages" => $language->id ]); ?>"><?php echo $language->name; ?></a></td>
            <td><?php echo $language->localized_name; ?></td>
            <td><?php echo $language->lang_code; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="<?php $helper->routing->route([ "languages" ] , "add"); ?>" class="button">Add language</a></p>
