<h2>Language</h2>

<table class="detail table">
    <tr>
        <td>Name</td>
        <td><?php echo $item->name; ?></td>
    </tr>
    <tr>
        <td>Localized name</td>
        <td><?php echo $item->localized_name; ?></td>
    </tr>
    <tr>
        <td>Language code</td>
        <td><?php echo $item->lang_code; ?></td>
    </tr>
</table>

<p>
    <a href="<?php $helper->routing->route([ "languages" => $item->id ], "edit"); ?>" class="button">Edit</a>
    <a href="<?php $helper->routing->route([ "languages" => $item->id ], "delete"); ?>" class="button">Delete</a>
</p>
<p><a href="<?php $helper->routing->route([ "languages" ]); ?>">Back to index</a></p>
