<h2>Add a product</h2>

<form method="post" action="/products/add">

    <?php $helper->form->textField($form->getField("title"), "Title"); ?>
    <?php $helper->form->textField($form->getField("sku"), "SKU"); ?>
    <?php $helper->form->textField($form->getField("gtin"), "GTIN"); ?>

    <button type="submit">Save</button>
    <button type="button" onclick="history.back()">Cancel</button>

</form>
