<h2>Delete the product</h2>

<p style="color: red;">Are you sure you want to delete this product? This can't be undone!</p>

<form method="post" action="<?php $helper->routing->route([ "products" => $item->id ] , "delete"); ?>">
    <input type="hidden" name="confirm" value="1" />
    <p>
        <button type="button" onclick="history.back()">Cancel</button>
        <button type="submit">Delete</button>
    </p>
</form>
