<h2>Product index</h2>

<table class="index table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Type</th>
            <th>Base price</th>
            <th>SKU</th>
            <th>GTIN</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $product): ?>
        <tr>
            <td><a href="/products/<?php echo $product->id; ?>"><?php echo $product->title; ?></a></td>
            <td><?php echo $product->product_type; ?></td>
            <td><?php echo $product->base_price; ?></td>
            <td><?php echo $product->sku; ?></td>
            <td><?php echo $product->gtin; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="/products/add" class="button">Add product</a></p>
