<h2>Product</h2>

<ul class="tabs">
<?php foreach ($subnav->getChildren() as $node): ?>
    <li <?php if ($node->active) echo ' class="active"'; ?>><a href="<?php echo $node->url; ?>"><?php echo $node->label; ?></a></li>
<?php endforeach; ?>
</ul>

<table class="detail table">
    <tr>
        <td>Title</td>
        <td><?php echo $item->title; ?></td>
    </tr>
    <tr>
        <td>Type</td>
        <td><?php echo $item->product_type->name; ?></td>
    </tr>
    <tr>
        <td>Base price</td>
        <td><?php echo $item->base_price; ?></td>
    </tr>
    <tr>
        <td>SKU</td>
        <td><?php echo $item->sku; ?></td>
    </tr>
    <tr>
        <td>GTIN</td>
        <td><?php echo $item->gtin; ?></td>
    </tr>
</table>

<p>
    <a href="<?php $helper->routing->route([ "products" => $item->id ], "edit"); ?>" class="button">Edit</a>
    <a href="<?php $helper->routing->route([ "products" => $item->id ], "delete"); ?>" class="button">Delete</a>
</p>
<p><a href="<?php $helper->routing->route([ "products" ]); ?>">Back to index</a></p>
