<h2>Product</h2>

<p>
    Title: <?php echo $item->title; ?><br/>
    Type: <?php echo $item->product_type->name; ?><br/>
    SKU: <?php echo $item->sku; ?><br/>
    GTIN: <?php echo $item->gtin; ?>
</p>

<p>
    <a href="/products/<?php echo $item->id; ?>/edit">Edit</a>
    &middot;
    <a href="/products/<?php echo $item->id; ?>/delete">Delete</a>
</p>
<p><a href="/products">Back to index</a></p>
