<h2>Product</h2>

<table>
    <tr>
        <td>Title</td>
        <td><?php echo $item->title; ?></td>
    </tr>
    <tr>
        <td>Type</td>
        <td><?php echo $item->product_type->name; ?></td>
    </tr>
    <tr>
        <td>Base price</td>
        <td><?php echo $item->base_price; ?></td>
    </tr>
    <tr>
        <td>SKU</td>
        <td><?php echo $item->sku; ?></td>
    </tr>
    <tr>
        <td>GTIN</td>
        <td><?php echo $item->gtin; ?></td>
    </tr>
</table>

<p>
    <a href="/products/<?php echo $item->id; ?>/edit">Edit</a>
    &middot;
    <a href="/products/<?php echo $item->id; ?>/delete">Delete</a>
</p>
<p><a href="/products">Back to index</a></p>
