<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Webshop Management</title>
    <style>
        .sidebar {
            width: 320px;
            border-right: 1px solid #ebebeb;
            float: left;
        }

        .content {
            margin-left: 320px;
            padding: 0 20px 0 20px;
        }

        .errors {
            color: red;
        }

        .tabs {
            margin: 0 -10px 1rem -10px;
            padding: 0;
            list-style: none;
            display: flex;
            border-bottom: 1px solid #ebebeb;
        }
        .tabs li {
            display: block;
            margin-bottom: -1px;
        }
        .tabs li a {
            display: block;
            padding: 8px 10px;
            border-bottom: 3px solid transparent;
            color: #666;
            text-decoration: none;
        }
        .tabs li a:hover {
            color: #000;
        }
        .tabs li.active a {
            color: #000;
            border-bottom-color: #000;
        }
    </style>
</head>
<body>
    <h1>Webshop</h1>

    <div class="sidebar">
        <ul>
            <li>
                <a href="/products">Products</a>
                <ul>
                    <li><a href="/product-types">Types</a></li>
                </ul>
            </li>
            <li>
                <a href="/settings">Settings</a>
                <ul>
                    <li><a href="/channels">Channels</a></li>
                    <li><a href="/languages">Languages</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <div class="content">
        <?php echo $content; ?>
    </div>
</body>
</html>
