<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Webshop Management</title>
    <style>
        .sidebar {
            width: 320px;
            border-right: 1px solid #ebebeb;
            float: left;
        }

        .content {
            margin-left: 320px;
            padding-left: 20px;
        }

        .errors {
            color: red;
        }
    </style>
</head>
<body>
    <h1>Webshop</h1>

    <div class="sidebar">
        Sidebar
    </div>
    <div class="content">
        <?php echo $content; ?>
    </div>
</body>
</html>
