<h2>Channels</h2>

<table class="index table">
    <thead>
        <tr>
            <th>Channel</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $channel): ?>
        <tr>
            <td><a href="<?php $helper->routing->route([ "channels" => $channel->id ]); ?>"><?php echo $channel->name; ?></a></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="<?php $helper->routing->route([ "channels" ], "add"); ?>" class="button">Add channel</a></p>
