<h2>Channel</h2>

<table>
    <tr>
        <td>Name</td>
        <td><?php echo $item->name; ?></td>
    </tr>
</table>

<p>
    <a href="<?php $helper->routing->route([ "channels" => $item->id ], "edit"); ?>" class="button">Edit</a>
    <a href="<?php $helper->routing->route([ "channels" => $item->id ], "delete"); ?>" class="button">Delete</a>
</p>
<p><a href="<?php $helper->routing->route([ "channels" ]); ?>">Back to index</a></p>
