<h2>Attributes for <?php echo $parentItem->name; ?></h2>

<ul class="tabs">
<?php foreach ($subnav->getChildren() as $node): ?>
    <?php if (!$node->hidden): ?>
    <li <?php if ($node->active) echo ' class="active"'; ?>><a href="<?php echo $node->url; ?>"><?php echo $node->label; ?></a></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>

<table class="index table">
    <thead>
        <tr>
            <th>Attribute</th>
            <th>Type</th>
            <th>Array</th>
            <th>Targeted</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $attribute): ?>
        <tr>
            <td><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes" => $attribute->id ]); ?>"><?php echo $attribute->name; ?></a></td>
            <td><?php echo $attribute->data_type; ?></td>
            <td><?php echo $attribute->is_array ? 'yes' : 'no'; ?></td>
            <td><?php echo $attribute->is_targeted ? 'yes' : 'no'; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes"] , "add"); ?>" class="button">Add attribute</a></p>
