<h2>Attributes for <?php echo $parentItem->name; ?></h2>

<ul class="tabs">
    <li><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id ]); ?>">Product type</a></li>
    <li><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id ] , "edit"); ?>">Edit</a></li>
    <li class="active"><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes" ]); ?>">Attributes</a></li>
</ul>

<table class="index table">
    <thead>
        <tr>
            <th>Attribute</th>
            <th>Type</th>
            <th>Array</th>
            <th>Targeted</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($items as $attribute): ?>
        <tr>
            <td><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes" => $attribute->id ]); ?>"><?php echo $attribute->name; ?></a></td>
            <td><?php echo $attribute->data_type; ?></td>
            <td><?php echo $attribute->is_array ? 'yes' : 'no'; ?></td>
            <td><?php echo $attribute->is_targeted ? 'yes' : 'no'; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<p><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes"] , "add"); ?>" class="button">Add attribute</a></p>
