<h2>Attribute</h2>

<ul class="tabs">
<?php foreach ($subnav->getChildren() as $node): ?>
    <?php if (!$node->hidden): ?>
    <li <?php if ($node->active) echo ' class="active"'; ?>><a href="<?php echo $node->url; ?>"><?php echo $node->label; ?></a></li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>

<table class="detail table">
    <tr>
        <td>Name</td>
        <td><?php echo $item->name; ?></td>
    </tr>
    <tr>
        <td>Type</td>
        <td><?php echo $item->data_type; ?></td>
    </tr>
    <tr>
        <td>Is array</td>
        <td><?php echo $item->is_array ? 'yes' : 'no'; ?></td>
    </tr>
    <tr>
        <td>Units</td>
        <td><?php echo $item->units; ?></td>
    </tr>
    <tr>
        <td>Is targeted</td>
        <td><?php echo $item->is_targeted ? 'yes' : 'no'; ?></td>
    </tr>
</table>

<p>
    <a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes" => $item->id ] , "edit"); ?>" class="button">Edit</a>
    <a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes" => $item->id ] , "delete"); ?>" class="button">Delete</a>
</p>
<p><a href="<?php $helper->routing->route([ "product-types" => $parentItem->id, "attributes"  ]); ?>">Back to index</a></p>
